Refactor names
assignment-exec/image-builder pull request #26
Opened 2020-05-20 12:55 UTC by balandi1

- Renamed functions, types and other variables wherever necessary.
- Merging of this request closes Issue 23.

2020-05-21 17:02 UTC, pradykaushik requested changes
Use the review comments when refactoring.

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
> +	IsImagePresent         bool
`ImageExists` works just fine for this.

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
>  			return errors.New("assignment assignCfgs not provided")
error message is confusing.

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
> +	username, hasFound := os.LookupEnv(environment.DockerAuthUsername)
change `hasFound` to `usernameFound`

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
> +	hasFound = false
the name of the variable should indicate what has/hasn't been found.

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
>  		return errors.New("code-runner base image not found on docker registry")
is this error message correct?

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
> +	assgnEnv.DockerfileInstructions.WriteString(assgnEnv.AssgnEnvConfig.WriteInstruction())
Shouldn't all the [WriteInstruction(...) functions here](https://github.com/balandi1/image-builder/blob/issues/issue-23-refactor-names/configurations/assignmentEnvConfig.go) be renamed to `GetInstruction(...)`? Those methods are only returning the instructions and not persisting them anywhere.

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
>  func (assgnEnv *assignmentEnvironment) writeFromDependencies() {
Can we rewrite this function to avoid `strings.Join(...)` in a loop and to avoid any trailing newline characters while writing instructions to the dockerfile? Below is an example.
If you agree with this, then follow a similar design for the other `writeXXX(...)` functions as well.
```go

func (assgnEnv *assignmentEnvironment) writeFromDependencies() {
	var instructions []string
	
	// FROM instruction.
	instructions = append(instructions, fmt.Sprintf("FROM %s", assgnEnv.ImgBuildConfig.imageTag))
	// COPY instruction.
	instructions = append(instructions, fmt.Sprintf("COPY . /" + constants.CodeRunnerDir))

	var imageTagParts []string
	for lib, installCmd := range assgnEnv.AssgnEnvConfig.Deps.Libraries {
		// Append library names to image tag.
		imageTagParts = append(imageTagParts, lib)
		
		// RUN instruction.
		instructions = append(instructions, "RUN " + installCmd.WriteInstruction() + " " + lib)
	}
	// Building image tag.
	assgnEnv.ImgBuildConfig.imageTag = strings.Join([]string{assgn.ImgConfig.imageTag, 
		strings.Join(imageTagParts, "-")}, "-")
	assgnEnv.DockerfileInstructions.WriteString(strings.Join(instructions, "\n"))
}
```

2020-05-21 17:02 UTC, pradykaushik commented on builder/assignmentEnv.go
> +	if !assgnEnv.IsImagePresent && assgnEnv.ImgBuildConfig.isPublish {
`isPublish` sounds odd.

2020-05-21 17:02 UTC, pradykaushik commented on builder/command.go
> +	var cmdStack []command
preferable not to include the type of the data structure as part of the variable name. Otherwise, if we ever change the data structure used, the variable name will also need to be changed.

2020-05-21 17:02 UTC, pradykaushik commented on main.go
> +var assignmentEnvConfigFilepath = flag.String("assignmentEnvConfig", "assignment-env.yaml", "Assignment Environment configuration filepath")
flag hasn't been renamed.

2020-05-25 15:43 UTC, balandi1 commented on builder/assignmentEnv.go
> +	IsImagePresent         bool
Okay

2020-05-25 15:44 UTC, balandi1 commented on builder/assignmentEnv.go
>  			return errors.New("assignment assignCfgs not provided")
Changed

2020-05-25 15:44 UTC, balandi1 commented on builder/assignmentEnv.go
> +	username, hasFound := os.LookupEnv(environment.DockerAuthUsername)
Done

2020-05-25 15:45 UTC, balandi1 commented on builder/assignmentEnv.go
> +	hasFound = false
Done

2020-05-25 15:47 UTC, balandi1 commented on builder/assignmentEnv.go
>  		return errors.New("code-runner base image not found on docker registry")
No. It should be language image.

2020-05-25 15:49 UTC, balandi1 commented on builder/assignmentEnv.go
> +	assgnEnv.DockerfileInstructions.WriteString(assgnEnv.AssgnEnvConfig.WriteInstruction())
Yes. Agreed.

2020-05-25 15:53 UTC, balandi1 commented on builder/assignmentEnv.go
> +	if !assgnEnv.IsImagePresent && assgnEnv.ImgBuildConfig.isPublish {
Okay. Then I think I should change it back to publishImage, or isPublishEnabled ?

2020-05-25 15:59 UTC, balandi1 commented on builder/command.go
> +	var cmdStack []command
Okay

2020-05-25 15:59 UTC, balandi1 commented on main.go
> +var assignmentEnvConfigFilepath = flag.String("assignmentEnvConfig", "assignment-env.yaml", "Assignment Environment configuration filepath")
Done

2020-05-25 16:03 UTC, balandi1 commented on builder/assignmentEnv.go
>  func (assgnEnv *assignmentEnvironment) writeFromDependencies() {
Okay. Agreed.

2020-05-25 19:57 UTC, pradykaushik approved these changes
Overall LGTM. Just a minor fix and then we can merge it in.

2020-05-25 19:57 UTC, pradykaushik commented on builder/assignmentEnv.go
> +		// Append library names to an array.
unnecessary comment.

2020-05-26 15:02 UTC, balandi1 commented on builder/assignmentEnv.go
> +		// Append library names to an array.
Done

2020-05-26 16:22 UTC, merged