Makefile and workflow actions
assignment-exec/image-builder pull request #4
Opened 2020-04-06 18:09 UTC by balandi1

- Makefile for building, running and testing the image builder.

2020-04-12 05:19 UTC, pradykaushik requested changes
once pull request #2 has been merged, rebase and update this PR.

2020-04-13 20:34 UTC, pradykaushik requested changes

2020-04-13 20:34 UTC, pradykaushik commented on .github/workflows/actions.yml
> +      run: go test ./...
change to `make test-verbose`?

2020-04-13 20:34 UTC, pradykaushik commented on Makefile
> +
add another target for verbose testing.

```
test-verbose:
        $(GOTEST) -v ./...
```

2020-04-13 21:35 UTC, balandi1 commented on .github/workflows/actions.yml
> +      run: go test ./...
okay

2020-04-13 21:35 UTC, balandi1 commented on Makefile
> +
okay

2020-04-17 03:17 UTC, pradykaushik approved these changes

2020-04-19 19:25 UTC, merged